# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9decd7388bc54e8c8debb640ea8b13b9a04ab436c3b5ea0f8a2817586ac73cb157d0238108182620874467cb22a6953856ed540a99fa4f0a1037ff2eb34bd818

test:
  secret_key_base: 961d3392e94504cac28324e2e4d13a914a1c9c9f8b75fe0f153a622e62d6b2e554b5930d73630d6874084469c953b6ad5ae134e16e432e6322630e5c97333547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
